# fly.toml app configuration file generated for poker-nights on 2026-02-27T08:45:21Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'poker-nights'
primary_region = 'ams'

[env]
  DATA_DIR = "/data"
  PORT = "8080"
  HOSTNAME = "0.0.0.0"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
